version: '3'

services:
  server:
    image: node:18-alpine
    build:
      context: ../../server
      dockerfile: Dockerfile
    container_name: server
    working_dir: /app
    restart: unless-stopped
    ports:
      - 127.0.0.1:4444:4444
    volumes:
      - ../../server:/app
    networks:
      - app-network
    depends_on:
      - mongodb
  
  mongodb:
    container_name: $MONGODB_CONTAINER_NAME
    image: mongo:7.0.6
    env_file: ./.env
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: $MONGODB_ROOT_USERNAME
      # MONGO_INITDB_ROOT_PASSWORD: $MONGODB_ROOT_PASSWORD
      # MONGO_INITDB_DATABASE: $MONGODB_DATABASE
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - todo-db:/data/db
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx/nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - server
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email medifman@gmail.com --agree-tos --no-eff-email --force-renewal -d pavlo-pylypchuk.com -d www.pavlo-pylypchuk.com
    depends_on:
      - webserver

volumes:
  todo-db:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/madman/node_project/views/
      o: bind
  dhparam:
   driver: local
   driver_opts:
     type: none
     device: /home/madman/node_project/dhparam/
     o: bind

networks:
  app-network:
    driver: bridge

